export const currency = '$';
export const currentYear = new Date().getFullYear();
export const developedByLink = 'https://nextmedia.ae/';
export const developedBy = 'Next Media';
export const contactUs = 'info.nextdms@gmail.com';
export const buyLink = '';
export const basePath = '';
export const DEFAULT_PAGE_TITLE = 'TMG GLOBAL | Responsive Admin Dashboard';
export const colorVariants = ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'dark', 'purple', 'pink', 'orange', 'light', 'link'];